export const PKG_PREFIX = '@humble-ui'
export const PKG_NAME = 'humble-ui'
export const PKG_CAMELCASE_NAME = 'HumbleUI'
export const PKG_CAMELCASE_LOCAL_NAME = 'HumbleUILocale'
export const PKG_BRAND_NAME = 'Humble UI'
